a17-sidebar
selsa-inube/bootcamp-jul pull request #103
Opened 2024-08-01 08:37 UTC by Juanmediina

Creation of sidebar

2024-08-01 19:49 UTC, Iregui44 requested changes

2024-08-01 19:49 UTC, Iregui44 commented on src/jm/html-css/style.css
> +
Theres is no hover pseduclass or anything that match the behaviour we expect when you hover over the logos.

2024-08-01 19:49 UTC, Iregui44 commented on src/jm/html-css/index.html
> +                <span class="title">Hostiry</span>
```suggestion
                <span class="title">History</span>
```

2024-08-02 05:00 UTC, Juanmediina commented on src/jm/html-css/style.css
> +
Added pseudoclass on hover

2024-08-02 07:13 UTC, Iregui44 commented on src/jm/html-css/index.html
> +                <span class="title">Histiry</span>
```suggestion
                <span class="title">History</span>
```

2024-08-02 07:15 UTC, Iregui44 commented on html-css/index.html
> +  <head>
What is this file?

2024-08-02 07:16 UTC, Iregui44 commented on src/jm/html-css/style.css
> +.menu-item:hover .tooltip {
hover is not working, when I hover over the icon the menu does not appear.

2024-08-05 15:51 UTC, Juanmediina commented on src/jm/html-css/index.html
> +                <span class="title">Hostiry</span>
ok

2024-08-05 15:51 UTC, Juanmediina commented on src/jm/html-css/index.html
> +                <span class="title">Histiry</span>
ok

2024-08-05 15:51 UTC, Juanmediina commented on html-css/index.html
> +  <head>
deleted file

2024-08-05 15:52 UTC, Juanmediina commented on src/jm/html-css/style.css
> +.menu-item:hover .tooltip {
correction made

2024-08-06 10:58 UTC, Iregui44 approved these changes

2024-08-16 08:32 UTC, Iregui44 commented
You have conflicting errors please fix them to be able to marge

2024-10-02 12:59 UTC, closed without merging