a3-press-release
selsa-inube/bootcamp-jul pull request #44
Opened 2024-07-16 17:38 UTC by Juanmediina

Creacion de la pagina A3 press release

2024-07-27 10:14 UTC, Iregui44 requested changes

2024-07-27 10:14 UTC, Iregui44 commented on src/jm/html-css/a3-press-release/index.html
> +    <div class="article">
I think you whould try ang use more html tags and less div tags, Lets say article tag may be great here.

2024-07-27 10:14 UTC, Iregui44 commented on src/jm/html-css/a3-press-release/style.css
> +.text-grey {
Space?

2024-07-27 10:14 UTC, Iregui44 commented on src/jm/html-css/a3-press-release/style.css
> +img {
Space?

2024-07-27 10:14 UTC, Iregui44 commented on src/jm/html-css/a3-press-release/style.css
> +  display: inline-block;
Maybe add margin? I dont see the img in the center, or any other part for waht matters.

2024-07-27 10:14 UTC, Iregui44 commented on src/jm/html-css/a3-press-release/style.css
> +.article {
Review this styles as the page dont look anything as the example

2024-07-27 10:14 UTC, Iregui44 commented on src/jm/html-css/a3-press-release/index.html
> +</html>
Missing press contact

2024-07-27 10:14 UTC, Iregui44 commented on src/jm/html-css/a3-press-release/style.css
> +h2 {
Review this styles as the page dont look anything as the example

2024-07-27 10:20 UTC, Iregui44 commented on src/jm/html-css/a3-press-release/index.html
> +    <link rel="stylesheet" href="style.css" />
File usually called styles. Just a TOC :)

2024-07-31 04:38 UTC, Juanmediina commented on src/jm/html-css/a3-press-release/index.html
> +    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
change made

2024-07-31 04:38 UTC, Juanmediina commented on src/jm/html-css/a3-press-release/index.html
> +      src="https://www.apple.com/newsroom/images/product/apple-tv-plus/standard/Apple-Emmy-winner-Sept-2022-Ted-Lasso_big.jpg.large_2x.jpg"
added attribute

2024-07-31 04:40 UTC, Juanmediina commented on src/jm/html-css/a3-press-release/index.html
> +    <div class="article">
the label change has been made

2024-07-31 04:40 UTC, Juanmediina commented on src/jm/html-css/a3-press-release/style.css
> +.text-grey {
ok

2024-07-31 04:40 UTC, Juanmediina commented on src/jm/html-css/a3-press-release/style.css
> +img {
ok

2024-07-31 04:40 UTC, Juanmediina commented on src/jm/html-css/a3-press-release/style.css
> +  display: inline-block;
added margin

2024-07-31 04:41 UTC, Juanmediina commented on src/jm/html-css/a3-press-release/style.css
> +.article {
corrections made

2024-07-31 04:41 UTC, Juanmediina commented on src/jm/html-css/a3-press-release/index.html
> +</html>
the contact press has been created

2024-07-31 04:41 UTC, Juanmediina commented on src/jm/html-css/a3-press-release/style.css
> +h2 {
corrections made

2024-08-01 09:20 UTC, Iregui44 approved these changes

2024-08-14 10:27 UTC, merged