a9-float layout
selsa-inube/bootcamp-jul pull request #74
Opened 2024-07-26 04:49 UTC by Juanmediina

Creacion de actividad a9 float-layout

2024-07-27 10:56 UTC, Iregui44 requested changes

2024-07-27 10:56 UTC, Iregui44 commented on src/jm/html-css/style.css
> +  background-image: url(./image/2.png);
I dont see the use of float anywhere

2024-07-27 10:56 UTC, Iregui44 commented on src/jm/html-css/index.html
> +    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
```suggestion
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
```

2024-07-27 10:56 UTC, Iregui44 commented on src/jm/html-css/index.html
> +            <li><a href="#">My playlist #1</a></li>
I think you are missing a Ul tag here

2024-07-31 05:09 UTC, Juanmediina commented on src/jm/html-css/style.css
> +  background-image: url(./image/2.png);
use of float has already been added

2024-07-31 05:09 UTC, Juanmediina commented on src/jm/html-css/index.html
> +    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
corrected

2024-07-31 05:09 UTC, Juanmediina commented on src/jm/html-css/index.html
> +            <li><a href="#">My playlist #1</a></li>
UI has been added

2024-08-01 09:24 UTC, Iregui44 approved these changes

2024-08-14 10:28 UTC, merged